[package]
name = "packing2d"
version = "0.1.0"
authors = ["Brandon Surmanski <b.surmanski@gmail.com>"]
edition = "2018"

[dependencies]
sdl2 = {version = "0.32.1", features = ["bundled", "static-link"]}
gl = {version = "0.10.0"}
nalgebra = "0.16.13"
